### ISSUE TITLE
error when trying to get multiple codes or an identifier

### ISSUE THREAD

**Issue by lunarbase** [fastlane/codes#12]
I have this error saying "wrong password" when I do `codes 4` or `codes 4 -a com.myCompany.myApp`. There is no password problem because I can use all other fastlane apps and this just works if I simply type `codes`.

DEBUG [2015-05-22 12:53:28.55]: Looks like your login data was correct, but you do not have access to the apps.
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.7.2/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:51:in `rescue in login': Error logging in user xxxxxxxxxx with the given password. Make sure you entered them correctly. (FastlaneCore::ItunesConnect::ItunesConnectLoginError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.7.2/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:40:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.7.2/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/lib/codes/codes_runner.rb:4:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/lib/codes/codes_runner.rb:4:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/bin/codes:43:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/bin/codes:78:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/bin/codes:82:in `<top (required)>'
	from /usr/bin/codes:23:in `load'
	from /usr/bin/codes:23:in `<main>'

**Comment by lacostej** [comment]
The error message is **"Looks like your login data was correct, but you do not have access to the apps."**

Are you sure your user has Admin role ? [It is required to access the promo codes](https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/ProvidingPromoCodes.html)
