### ISSUE TITLE
you get error on any app that is pending developer release  works on live app this just started the last few days

### ISSUE THREAD

**Issue by sfransen** [fastlane/codes#13]
I changed my aped to xxxx.xxx in this error message but this is the error I get.

/Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/lib/codes/itunes_connect.rb:22:in `run': Could not find app using the following information: {:number_of_codes=>1, :app_identifier=>"com.xxxx.xxxx", :apple_id=>nil, :output_file_path=>nil, :urls=>nil}. Maybe the app is not in the store. Pass the Apple ID of the app as well! (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/lib/codes/codes_runner.rb:4:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/bin/codes:43:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/bin/codes:78:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/bin/codes:82:in `<top (required)>'
	from /usr/bin/codes:23:in `load'
	from /usr/bin/codes:23:in `<main>'

**Comment by sfransen** [comment]
I figure out a fix for this. I will test it some more and then sent a push request.

**Comment by KrauseFx** [comment]
Thank you @sfransen

**Comment by sfransen** [comment]
I waiting on a apple to approve one of my app again so I can test this again.
 Sorry my last one was rejected and had to put a new build again.
