### ISSUE TITLE
fails if contract agreement required

### ISSUE THREAD

**Issue by lacostej** [fastlane/codes#16]
Code fails with
`````
/Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/fastlane_core-0.11.1/lib/fastlane_core/itunes_connect/itunes_connect_helper.rb:76:in `wait_for_elements': Couldn't find element 'input[type=checkbox]' after waiting for quite some time (FastlaneCore::ItunesConnect::ItunesConnectGeneralError)
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/codes-0.2.2/lib/codes/itunes_connect.rb:44:in `run'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `run'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/codes-0.2.2/bin/codes:43:in `block (2 levels) in run'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/codes-0.2.2/bin/codes:78:in `run'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/gems/codes-0.2.2/bin/codes:85:in `<top (required)>'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/bin/codes:23:in `load'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/bin/codes:23:in `<main>'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
`````

we have an error in the HTML that could allow displaying better error info:
`````
              <span id="headerMessagesUpdateContainer" class="lcAjaxContainer" action="/WebObjects/iTunesConnect.woa/wo/58.0.0.11.5.0.9.1" errorId="ajaxContainerError">
                <div id="warningMessageDiv">
                </div>
                    <div id="LCPurpleSoftwarePageWrapperErrorMessage" class="global-message error">
                      <div class="top"></div>
                      <div class="middle">
                        <img src="https://itc.mzstatic.com/itc/images/icon-red-error.png" alt="Warning Icon" width="38" height="37" class="error-icon" />
                        <div class="heading">The following error(s) occurred:</div>
                        <ul>
                            <li><span>An updated agreement is available. Before you can request promo codes, you must agree to the new terms in <a href='/WebObjects/iTunesConnect.woa/wa/jumpTo?page=contracts'>Agreements, Tax, and Banking</a>.</span></li>
                        </ul>
                      </div>
                      <div class="bottom"></div>
                    </div>
`````

**Comment by lacostej** [comment]
I have the same error but this time, there's no agreement preventing the download. The server had generated the downloads. I will have to troubleshoot this further.

**Comment by KrauseFx** [comment]
:+1:
