### ISSUE TITLE
codes will not login in you get error of "Error logging in user xxxxxx@xxxxxx.com with the given password. Make sure you entered them correctly."

### ISSUE THREAD

**Issue by sfransen** [fastlane/codes#18]
[18:50:34]: ["/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.12.0/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:41:in `login'", "/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.12.0/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `new'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `run'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:43:in `block (2 levels) in run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:78:in `run'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:85:in `<top (required)>'", "/usr/bin/codes:23:in `load'", "/usr/bin/codes:23:in `<main>'"]
[18:50:55]: ["/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.12.0/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:42:in `login'", "/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.12.0/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `new'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `run'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:43:in `block (2 levels) in run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:78:in `run'", "/Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:85:in `<top (required)>'", "/usr/bin/codes:23:in `load'", "/usr/bin/codes:23:in `<main>'"]
[18:50:55]: Couldn't find element '.ng-scope' after waiting for quite some time
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.12.0/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:55:in `rescue in login': Error logging in user xxxxxx@xxxxxx.com with the given password. Make sure you entered them correctly. (FastlaneCore::ItunesConnect::ItunesConnectLoginError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.12.0/lib/fastlane_core/itunes_connect/itunes_connect_login.rb:40:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.12.0/lib/fastlane_core/itunes_connect/itunes_connect.rb:62:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:43:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:78:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:85:in `<top (required)>'
	from /usr/bin/codes:23:in `load'
	from /usr/bin/codes:23:in `<main>'

**Comment by sfransen** [comment]
I tried using the saved password and also manually entered it in.
neither one worked same error

**Comment by lacostej** [comment]
try

``````
rm /tmp/spaceship*
``````

**Comment by sfransen** [comment]
There is nothing there

**Comment by lacostej** [comment]
@sfransen I had updated the message you replied to and you might not have seen my full answer in your mail.

Try

``````
gem update fastlane_core
```````

**Comment by sfransen** [comment]
Ok I will try that thank again

**Comment by sfransen** [comment]
Thanks I can log on now 
but I now getting error  on the Accepting the App Store Volume Custom Code Agreement
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/itunes_connect.rb:48:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/lib/codes/codes_runner.rb:4:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:43:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:78:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.2/bin/codes:85:in `<top (required)>'
	from /usr/bin/codes:23:in `load'
	from /usr/bin/codes:23:in `<main>'

**Comment by KrauseFx** [comment]
@sfransen That's probably because you haven't signed the `App Store Volume Custom Code Agreement`. Just login on iTunes Connect and try to issue a promo code manually and you should get redirected to the form to sign.

**Comment by sfransen** [comment]
I need this  that was not the problem  but I got it to work now.
Thanks

**Comment by KrauseFx** [comment]
Cool :+1:
