### ISSUE TITLE
error downloading 1 code with Apple ID of the app and also using the simple command "codes"

### ISSUE THREAD

**Issue by posix88** [fastlane/codes#24]
Hello i'm stuck with these two issues, that prevents me to automatically download promo codes.
these are the two crash logs:

codes 1 -i ********* -X
[10:58:13]: Logging into iTunesConnect
[10:58:29]: Successfully logged into iTunesConnect
[10:58:29]: Downloading 1 promo code...
/Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/lib/codes/itunes_connect.rb:80:in `app_platform': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/lib/codes/itunes_connect.rb:147:in `fetch_app_data'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/lib/codes/itunes_connect.rb:15:in `download'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/lib/codes/codes_runner.rb:4:in `download'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/bin/codes:33:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/bin/codes:51:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/bin/codes:118:in `<top (required)>'
	from /usr/local/bin/codes:23:in `load'
	from /usr/local/bin/codes:23:in `<main>'

codes
[10:56:30]: Logging into iTunesConnect
[10:56:46]: Successfully logged into iTunesConnect
[10:56:46]: Downloading 1 promo code...
/Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/lib/codes/itunes_connect.rb:143:in `fetch_app_data': Could not find app using the following information: {:number_of_codes=>1, :app_identifier=>"*****", :apple_id=>nil, :output_file_path=>nil, :format=>nil, :country=>nil}. Maybe the app is not in the store. Pass the Apple ID of the app as well! (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/lib/codes/itunes_connect.rb:15:in `download'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/lib/codes/codes_runner.rb:4:in `download'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/bin/codes:33:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/bin/codes:51:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.4.1/bin/codes:118:in `<top (required)>'
	from /usr/local/bin/codes:23:in `load'
	from /usr/local/bin/codes:23:in `<main>'

My fastlane version is the latest. Thank you for your great job!

**Comment by agentcooper75** [comment]
same problem here.

**Comment by KrauseFx** [comment]
Sorry, this tool is not working any more after the recent change on iTunes Connect.

**Comment by sfransen** [comment]
I used this almost every day it is working fine for me
I do has different code then you have in the github
I can tell you it works I just tested even just now



Sent from my iPhone5

On Oct 23, 2015, at 12:11 PM, Felix Krause <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, this tool is not working any more after the recent change on iTunes Connect.

**Comment by sfransen** [comment]
I am using this version and it works fine I just tested it
#######################################################################
# codes 0.4.1 is available. You are on 0.2.2.
# It is recommended to use the latest version.
# Update using 'sudo gem update codes'.
# To see what's new, open https://github.com/KrauseFx/codes/releases.
#######################################################################
 
Steven Fransen

**Comment by sfransen** [comment]
OK I see we just got the new code too and mine is not working any more too.
 They changed the entire process of getting promo code now . Why does Apple keep making these stupid changes for no reason.
