### ISSUE TITLE
fails at launch

### ISSUE THREAD

**Issue by lukebar** [fastlane/codes#25]
I'm trying to use codes independently of any of the other tools. I followed the installation instructions, but attempting to run codes with or without parameters results in:

(Running on El Capitan)

/usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- fastlane_core/itunes_connect/itunes_connect (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/codes-0.4.1/lib/codes/itunes_connect.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/codes-0.4.1/lib/codes.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/codes-0.4.1/bin/codes:5:in `<top (required)>'
	from /usr/local/bin/codes:23:in `load'
	from /usr/local/bin/codes:23:in `<main>'

**Comment by icorn** [comment]
The same here.

**Comment by nemo** [comment]
Same over here!

**Comment by KrauseFx** [comment]
As mentioned in the documentation, this tool currently does not work due to changes of iTunes Connect.

**Comment by sfransen** [comment]
Do you plan to fix it again?
