### ISSUE TITLE
0.2.0 doesn't seem to parse options properly

### ISSUE THREAD

**Issue by lacostej** [fastlane/codes#6]
````
lacostej@jeromes-mbp ~/Code/WWTK/DE.git (master) codes --version
codes 0.2.0
lacostej@jeromes-mbp ~/Code/WWTK/DE.git (master) codes -version
codes 0.2.0
lacostej@jeromes-mbp ~/Code/WWTK/DE.git (master) codes -help
Usage: codes [options]
lacostej@jeromes-mbp ~/Code/WWTK/DE.git (master) codes --help
(erb):2:in `get_binding': undefined method `size' for nil:NilClass (NoMethodError)
        from /Users/lacostej/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/erb.rb:850:in `eval'
        from /Users/lacostej/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/erb.rb:850:in `result'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.3.3/lib/commander/help_formatters/terminal.rb:7:in `render'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.3.3/lib/commander/runner.rb:302:in `block (2 levels) in create_default_commands'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.3.3/lib/commander/command.rb:153:in `run'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.3.3/lib/commander/runner.rb:57:in `block in run!'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.3.3/lib/commander/runner.rb:382:in `block in global_option_proc'
        from /Users/lacostej/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1359:in `call'
        from /Users/lacostej/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1359:in `block in parse_in_order'
        from /Users/lacostej/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1346:in `catch'
        from /Users/lacostej/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1346:in `parse_in_order'
        from /Users/lacostej/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1340:in `order!'
        from /Users/lacostej/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1432:in `permute!'
        from /Users/lacostej/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:1454:in `parse!'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.3.3/lib/commander/runner.rb:363:in `parse_global_options'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.3.3/lib/commander/runner.rb:65:in `run!'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.3.3/lib/commander/delegates.rb:15:in `run!'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/codes-0.2.0/bin/codes:78:in `run'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/codes-0.2.0/bin/codes:82:in `<top (required)>'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/bin/codes:23:in `load'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/bin/codes:23:in `<main>'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/lacostej/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
````

**Comment by KrauseFx** [comment]
Thanks for letting me know, I'll push a new version right now :+1:

**Comment by KrauseFx** [comment]
Published https://github.com/fastlane/codes/releases/tag/0.2.1 :rocket:
